require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/dogs", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Dog. As you add validations to Dog, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Dog.create! valid_attributes
      get dogs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      dog = Dog.create! valid_attributes
      get dog_url(dog)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_dog_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      dog = Dog.create! valid_attributes
      get edit_dog_url(dog)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Dog" do
        expect {
          post dogs_url, params: { dog: valid_attributes }
        }.to change(Dog, :count).by(1)
      end

      it "redirects to the created dog" do
        post dogs_url, params: { dog: valid_attributes }
        expect(response).to redirect_to(dog_url(Dog.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Dog" do
        expect {
          post dogs_url, params: { dog: invalid_attributes }
        }.to change(Dog, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post dogs_url, params: { dog: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested dog" do
        dog = Dog.create! valid_attributes
        patch dog_url(dog), params: { dog: new_attributes }
        dog.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the dog" do
        dog = Dog.create! valid_attributes
        patch dog_url(dog), params: { dog: new_attributes }
        dog.reload
        expect(response).to redirect_to(dog_url(dog))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        dog = Dog.create! valid_attributes
        patch dog_url(dog), params: { dog: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested dog" do
      dog = Dog.create! valid_attributes
      expect {
        delete dog_url(dog)
      }.to change(Dog, :count).by(-1)
    end

    it "redirects to the dogs list" do
      dog = Dog.create! valid_attributes
      delete dog_url(dog)
      expect(response).to redirect_to(dogs_url)
    end
  end
end
